[workspace]
resolver = "2"
members = [
    "imt-tree",
    "nf-server",
    "pir/client",
    "pir/export",
    "pir/server",
    "pir/test",
    "pir/types",
    "nf-ingest",
]

[workspace.dependencies]
imt-tree = { path = "imt-tree", version = "0.4.0", default-features = false }
voting-crypto-deps = { version = "=0.1.2", default-features = false }

[profile.release]
lto = "fat"
codegen-units = 1
